### ISSUE TITLE
must fix bugs

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#29]
- [ ] [p0] Balu -  kubernetes attempts to unmount a wrong vSphere volume and stops making any progress after that #37022 https://github.com/kubernetes/kubernetes/issues/37022

- [ ] [p0] Balu - vSphere Cloud Provider triggers panic in controller-manager pod https://github.com/kubernetes/kubernetes/issues/36295

- [ ] [p0] Abrar - vsphere volume does not honor fsGroup https://github.com/kubernetes/kubernetes/issues/34039

- [ ] [p0] Balu - vSphere cloudprovider does not sanitise region or failuredomain, so nodes fail to register https://github.com/kubernetes/kubernetes/issues/33576

- [ ] [p1] Balu - Space handling in path https://github.com/kubernetes/kubernetes/issues/37712. For now we can document the limitation.

- [ ] [p1] Abrar - vSphere Cloud Provider: Look into the need for credentials to be stored on nodes https://github.com/kubernetes/kubernetes/issues/35339

- [ ] [p2] vSphere Cloud provider: Volume detach is not issued when VM is not present https://github.com/kubernetes/kubernetes/issues/33061

**Comment by kerneltime** [comment]
Bugs tracked as independent issues https://github.com/vmware/kubernetes/issues
